google/reflectable.dart

reflectable/lib/src/reflectable_mirror_based.dart
This resolves https://github.com/dart-lang/reflectable/issues/40 although I did not add any tests (no existing test to build off of, and I didn't really want to write tests for the full InstanceInvokeMetaCapability...). This does unblock polymer though.
=> walk full super chain when checking for InstanceInvokeMetadataCapability

coverage_reflectable/pubspec.yaml, reflectable/lib/reflectable_builder.dart, reflectable/pubspec.yaml, test_reflectable/pubspec.yaml, test_reflectable/tool/build.dart
Turns out that the previous version looked OK, but a failure was masked (so nothing was built, but no information about the failure was returned so `annotated_steps.dart` thought it was all ok). This CL pushes the result information through the pipeline, and also solves the original problem by globbing the arguments given to build.dart.
=> Add glob dec17

tool/annotated_steps.dart
Still getting 'ProcessException: No such file or directory' on the package bot even though it's running locally. This CL just changes the file arguments to `build.dart` to use absolute paths.
=> Absolute paths dec17

reflectable/build.yaml, reflectable/lib/reflectable_builder.dart, reflectable/pubspec.yaml, test_reflectable/build.yaml, test_reflectable/pubspec.yaml
Here is an example of moving reflectable to the new package:build_runner config.
After this cl, most users of package:reflectable need only do `pub run build_runner build`, and reflectable will automatically bootstrap their application. They would still need to know to include the reflectable.dart file instead of the original one though.
We have some rough docs [here](https://github.com/dart-lang/build/tree/master/build_config#defining-builders-to-apply-to-dependents-similar-to-transformers) describing what this all does and are working on better ones.
See the example build.yaml I added to the test_reflectable package as well. Users can use the `generate_for` argument to change the primary inputs for the builder using that (this would be similar to the arguments the current build script …
=> update to latest package:build and add custom build.yaml

reflectable/lib/capability.dart, reflectable/lib/src/incompleteness.dart, reflectable/lib/src/transformer_implementation.dart
This PR introduces new methods in `ClassElementEnhancedSet` such that it again implements `Set<ClassElement>`. It also solves some typing issues arising because of new rules around `void`.
=> Dart 2 fixes

.status
TBR: During the 'flattening' of reflectable, the test files were moved from `test/mock_tests` to `test`. This CL updates `.status` to match that change.
=> Adjusted .status to match the new directory structure

CHANGELOG.md, pubspec.yaml
This is for publishing to provide access to the package version dependency update in the previous commit.
=> Preparing for release 2.0.1

lib/src/builder_implementation.dart, pubspec.yaml
For publishing on pub.dartlang.org as 2.0.3, just changing the pubspec.yaml description to fit in the recommended max size (180 chars), and removing the 'transformers:' section which is now unused.
=> Bumping version to 2.0.3

CHANGELOG.md, lib/reflectable_builder.dart, pubspec.yaml
Flutter depends on `analyzer` 0.33 and that requires a newer `build` (which is now at version 1.0.x), so there's a need to switch to more current versions of several packages in reflectable.
This PR does that; the APIs exported from `build` changed a bit, so the implementation of the builder in `reflectable_builder.dart` had to change somewhat.
The version number has been updated to 2.0.8, such that we can publish this commit directly.
=> Port reflectable to build 1.0.x

CHANGELOG.md, pubspec.yaml
Cf. issue #159, the version update to allow `0.34.*` is needed for angular >=5.2.0.
This update should make reflectable ready for release as 2.0.9.
This causes a somewhat inconvenient change in the behavior of `build_runner`: It refuses to generate code incrementally (and it writes out a large warning about this). This affects clients (maybe even clients who don't know that they are using reflectable indirectly), and they must add a direct dependency on the analyzer (it is _not_ enough that reflectable has it). I've asked Jacob how to deal with this without asking every direct or indirect client out there to edit their pubspec.yaml and add `analyzer: any`. But I think it makes sense to respond to #159 without having resolved this issue, and then fix it when we know how to do that.
We …
=> Updated analyzer dependency to allow 0.34.1

CHANGELOG.md, analysis_options.yaml, lib/capability.dart, lib/reflectable.dart, lib/reflectable_builder.dart, lib/src/builder_implementation.dart, lib/src/element_capability.dart, lib/src/reflectable_base.dart, lib/src/reflectable_builder_based.dart, pubspec.yaml
The package pana (which is used to compute the 'health' of packages on pub.dartlang.org and similar metrics) is unhappy about a number of things (e.g., `T x = null;` should be `T x;` and `{bool myOptionalParameter: false}` should be `{bool myOptionalParameter = false}`). This PR makes the requested changes.
Note that it includes `// ignore:deprecated_member_use` in the locations where we are using `computeNode` and `unit`. Those problems are real, but it will take a little longer to resolve them. Basically, Brian says that there is more than one user of the AST layer (that is, not the `Element` layer) that the analyzer package has traditionally provided, so there will be ways to keep doing the things that reflectable does via this layer&mdash;but we can't do it right now.
=> Pana fixes feb19

CHANGELOG.md, codereview.settings, example/example.dart, lib/reflectable_builder.dart, lib/src/builder_implementation.dart, lib/src/fixed_point.dart, pubspec.yaml, tool/publish
Cf. issue #173: Code generator updated to use new APIs for access to abstract syntax (`AstNode`) entities (`computeNode` cannot be used any more). This involves a major element of asynchrony, hence there are many changes of functions to be `async`, and of expressions to `await` a result.
The analyzer-as-used-by-build relies on summaries (rather than full libraries) for platform libraries ('dart:...' except 'dart:ui'). This means that it is not possible to obtain information about non-signature properties of platform code. See issue #180 for more details.
Note that the changes in `reflectable_builder.dart` were made to use the control flow shown in `build` package documentation.
This PR introduces a new version number: 2.1.0. This PR is the biggest rewrite of reflectable since 2016 (so it …
=> Update reflectable to enable analyzer 0.37.0

CHANGELOG.md, analysis_options.yaml, example/example.dart, lib/capability.dart, lib/reflectable_builder.dart, lib/src/builder_implementation.dart, lib/src/element_capability.dart, lib/src/fixed_point.dart, lib/src/incompleteness.dart, lib/src/reflectable_builder_based.dart, lib/src/reflectable_errors.dart, pubspec.yaml
Just a small cleanup from enabling pedantic checks: It mostly removes unnecessary `new` and `const` keywords from the code.
=> Use pedantic lints

lib/src/builder_implementation.dart
When using stagehand to generate your base structure, or when including pedantic two linting violations occur with the generated code:
- prefer_single_quotes
- always_declare_return_types
This pull request changes all double quotes to single quotes in generated code and adds the `void` return type to `initializeReflectable()`.
With these changes, `.reflectable.dart` files pass linting. Normally one would not worry so much about generated code, but currently dartanalyzer has a bug where the exclude option is not being processed properly, thus projects can not exclude certain code from analysis. (https://github.com/dart-lang/sdk/issues/29430)
=> Fix linting issues with generated code

CHANGELOG.md, lib/capability.dart, lib/mirrors.dart, lib/reflectable.dart, lib/reflectable_builder.dart, lib/src/builder_implementation.dart, lib/src/element_capability.dart, lib/src/fixed_point.dart, lib/src/incompleteness.dart, lib/src/reflectable_base.dart, lib/src/reflectable_builder_based.dart, lib/src/reflectable_class_constants.dart, lib/src/reflectable_errors.dart, pubspec.yaml
This PR changes many parts of the code in order to satisfy new linter requirements. In particular, it uses literal strings with single quotes whenever possible; it omits a number of type annotations on local variables (and introduces `ignore_for_file: omit_local_variable_type` in a couple of libraries, based on the judgment that the value of the type annotations for the reader of the code justifies keeping them).
The generated code now also contains a couple of `ignore_for_file` directives, such that the generated code does not get penalized for repeating structures from the target program (e.g., if a default value is `"a" + " string"` then we will copy that expression rather than simplifying it to `"a string"`, which will cause a linter complaint on the generated code).
Also, an actual …
=> Fix linter issues

pubspec.yaml
Tiny fix, only deletes 'author' field from pubspec.yaml (it is no longer recommended to have this field).
=> Removed author field from pubspec.yaml

CHANGELOG.md, lib/src/builder_implementation.dart, pubspec.yaml
This is just a temporary fix for issue #194, which is that reflectable breaks because the analyzer requires a new and different list of parameters for `InterfaceTypeImpl` construction. This CL just restricts the version of the analyzer.
The real solution is to pass the arguments as required for the invocations of the `InterfaceTypeImpl` constructor call, which will be done in a separate CL.
It may seem even better to avoid dependencies on `InterfaceTypeImpl` in the first place, but that may not be very helpful because we would then have to write a whole parallel hierarchy for a class hierarchy in the analyzer, and use these wrappers everywhere.
PS: This CL is intended to be published as version 2.2.1+1. This version _will_ be needed: If a client can use an analyzer with version '>=0.39.0 …
=> Adjusted dependencies to avoid the breaking constructor signature

CHANGELOG.md, lib/src/builder_implementation.dart, pubspec.yaml
This CL changes the invocations of the `InterfaceTypeImpl` in 'builder_implementation.dart' such that it compiles with analyzer 0.39.4.
However, the `MixinApplication` class does not model type arguments and type parameters properly, and there is no underlying model of this in the analyzer (because it doesn't model the classes created by mixin application directly). The language specification also does not make it explicit how exactly to deal with type parameters in a mixin application. So maybe we should change 'builder_implementation' to raise an error in some additional cases, and maybe we could then avoid calling this constructor at all. (As far as I remember, we needed to support `type`, but we could revisit that.)
The point around type parameters is that with `class A<X, Y> extends …
=> Adjust usage of InterfaceTypeImpl constructor to match analyzer 0.39.4 and up

CHANGELOG.md, lib/src/builder_implementation.dart, pubspec.yaml
Some usages of reflectable give rise to `implementation_imports` messages, cf. #203. Given that reflectable is intended to be able to import any library which contains a declaration that the developer has requested reflection support for, it seems reasonable to say that the generated code should be allowed to violate this lint without complaints. So this PR adds an `ignore_for_file` directive to get that effect.
=> Added lint exception about implementation_imports

CHANGELOG.md, lib/src/builder_implementation.dart, pubspec.yaml
The type `void` used to have no representation at run time, but Dart was updated a while back such that `void` is now reified. This PR changes the treatment of `void` as a `reflectedType` such that this reification is made available. Cf. #197.
=> Adding support for a reflected type reifying the type `void`

CHANGELOG.md, lib/reflectable_builder.dart, lib/src/builder_implementation.dart, pubspec.yaml
Cf. #210 and https://github.com/dart-lang/sdk/issues/42347, there is an issue with `sync*` getters, This PR works around that issue, and upgrades the analyzer version to 0.39.10.
Note that the "workaround" is adding `.toList()` at a point where several other similar expressions already have `.toList()`, which seems to be a reasonable approach anyway, and probably a bit faster. So there is no need to undo it when dart-lang/sdk#42347 is handled.
=> Update analyzer; work around sync* getter issue

reflectable/CHANGELOG.md, reflectable/lib/src/builder_implementation.dart, reflectable/pubspec.yaml
Issue #198 reports an `InconsistentAnalysisException` when code generation is performed with more than one entry point. A workaround came up in dart-lang/build#2634, and this PR uses that workaround, which does eliminate the dynamic errors. Prepared to publish as version 2.2.6.
=> Use workaround for 198

reflectable/CHANGELOG.md, reflectable/lib/src/builder_implementation.dart, reflectable/pubspec.yaml, test_reflectable/pubspec.yaml
Unfortunately, the published version 2.2.7 allows analyzer 0.40.3, but that version has a breaking change (affecting `ConstantEvaluator(..., ... /*This argument*/)`), so 2.2.7 only works with analyzers up to 0.40.2. This PR prepares publishing 2.2.8 which adapts the code to work after said change, and supports analyzer 0.40.3 - 0.40.4.
=> Fix constant evaluator invocation

reflectable/CHANGELOG.md, reflectable/pubspec.yaml
Issue #240 reports that some version resolutions fail now, because `dart_style` is available in a version with null safety, and reflectable doesn't allow for using that version. This PR enables that.
=> Update version of `dart_style`

reflectable/lib/reflectable_builder.dart, reflectable/lib/src/builder_implementation.dart, reflectable/lib/src/element_capability.dart, reflectable/pubspec.yaml, test_reflectable/tool/Makefile
This PR migrates the reflectable code generator to null safety, and it uses the newly arrived null safe versions of build packages, such that reflectable is fully opted in to null safety.
In general, nulls that arise because the program does not pass static analysis are asserted (so there are lots of ways that the code generation will crash with a null error if we run it on a program with errors). We may wish to change this later on, to avoid all those possible crashes.
However, it does not seem useful to replicate a large portion of error messages about Dart errors in any code generator, because it's just a duplicate of something that we already have in a much more complete form in the analyzer and the CFE. 
The best approach would probably be to ask the analyzer on startup whether this …
=> Use nullsafe build, migrate to null safety

reflectable/pubspec.yaml
Change pubspec.yaml to avoid depending on any versions of the form `*-nullsafety` (those packages do have a regular version with null safety now, and `pub publish` complains).
=> Remove pre-release deps (those packages do have a stable release now)

reflectable/CHANGELOG.md, reflectable/lib/src/builder_implementation.dart, reflectable/pubspec.yaml, test_reflectable/test/parameter_mirrors_test.dart
Remove a `!` and handle the null which may actually occur (fixing #253). Change the analyzer dependency to ^2.0.0, and perform a handful of changes that follow from this.
One test was changed (presumably a bug was fixed in the analyzer): An initializing formal parameter is now reported to be final, and a test expectation has been changed to reflect this new behavior.
=> Fix a null error; update dependencies

reflectable/CHANGELOG.md, reflectable/lib/src/builder_implementation.dart, reflectable/lib/src/reflectable_builder_based.dart, reflectable/pubspec.yaml, reflectable/tool/Makefile
This PR updates reflectable to use version 3.2.0 of the analyzer, and adjusts several locations in the code based on the fact that several getters/methods in the analyzer now return a non-null value (so we do not need to check for null any more). It updates the version number and CHANGELOG.md such that we can release reflectable 3.0.6 based on this commit.
=> Update reflectable to analyzer 3.2.0, cache some getters

reflectable/CHANGELOG.md, reflectable/lib/src/builder_implementation.dart, reflectable/lib/src/element_capability.dart, reflectable/pubspec.yaml, reflectable/tool/publish, test_reflectable/test/legacy/meta_reflector_test.dart, test_reflectable/test/legacy/meta_reflectors_user.dart, test_reflectable/test/legacy/mixin_test.dart, test_reflectable/test/meta_reflector_test.dart, test_reflectable/test/meta_reflectors_user.dart, test_reflectable/test/mixin_test.dart
The analyzer changed in several ways, and this migration gave rise to many changes. In particular, mixins and enums are no longer represented as `ClassElement`s with an `isEnum` and an `isMixin`, and this causes many changes to types and type tests.
=> Update analyzer to 5.0.0

reflectable/CHANGELOG.md, reflectable/lib/src/builder_implementation.dart, reflectable/pubspec.yaml
This PR changes reflectable such that it does not consider 'dart:html' as a library which can be imported by generated code. This used to be the case anyway, but build_resolvers 2.1.0 has added 'dart:html' to `resolver.libraries`, and this causes reflectable to generate code that imports 'dart:html' (and it has no notion about being on a platform where that library does or does not exist). Hence, this change preserves the behavior we have had until now.
The PR removes the workaround which was needed as described in https://github.com/google/reflectable.dart/issues/269. The InconsistentAnalysisException does not seem to occur any longer.
The PR also prepares reflectable for being released as version 4.0.2.
=> Update reflectable to use build_resolver 2.1.0

reflectable/CHANGELOG.md
I think it would be useful to adjust the links in the 4.0.5 CHANGELOG entry: I added a link to the DartDoc page for the `uri` getter itself, along with the link to the `AssetId` class. For the `packageConfig` getter, I added a link to the `package_config` package, whose README has a very good overview of what a package config file is in the first place, plus a link to the feature spec. I think it would be helpful to make those adjustments before 4.0.5 is published.
=> Adjust the documentation links given for the 4.0.5 CHANGELOG entry

reflectable/CHANGELOG.md, reflectable/example/example.dart, reflectable/lib/capability.dart, reflectable/lib/reflectable.dart, reflectable/lib/src/builder_implementation.dart, reflectable/lib/src/element_capability.dart, reflectable/lib/src/reflectable_builder_based.dart, reflectable/pubspec.yaml, test_reflectable/pubspec.yaml, test_reflectable/test/enum_test.dart, test_reflectable/test/generic_mixin_test.dart, test_reflectable/test/meta_reflector_test.dart, test_reflectable/test/meta_reflectors_domain.dart, test_reflectable/test/mixin_application_static_invoke_test.dart, test_reflectable/test/mixin_application_static_member_test.dart, test_reflectable/test/mixin_static_const_test.dart, test_reflectable/test/mixin_test.dart, test_reflectable/test/reflect_type_test.dart, test_reflectable/test/reflectors_test.dart, test_reflectable/test/serialize_test.dart, test_reflectable/test/subtype_quantify_test.dart, test_reflectable/test/subtype_test.dart
This PR changes reflectable such that it uses the analyzer version 6.4.0, and also updates other dependencies.
This includes several changes to the code associated with evaluation of constant expressions (where the new version of the analyzer does not support the approach which was used for this purpose previously).
=> Upgrade reflectable to use new version of analyzer

reflectable/CHANGELOG.md, reflectable/lib/src/builder_implementation.dart, reflectable/lib/src/reflectable_builder_based.dart, reflectable/pubspec.yaml, test_reflectable/pubspec.yaml
Update the package dependencies and resolve static analysis issues caused by this change.
In particular, remove several occurrences of named parameters that are now deprecated (e.g., `withNullability`), change invocations of `variable` to `variable2` (the analyzer package made this change in order to be able to migrate `variable` to a new semantics).
The new getter `variable2` has a nullable return type. It can only be null in the case where the given declaration is augmenting. Reflectable uses a defensive approach to handle these nulls, and it will most likely need to be updated when the augmentation feature is fully specified and implemented.
=> Update reflectable dependencies to use SDK 3.4.0 and analyzer 6.7.0

reflectable/CHANGELOG.md, reflectable/pubspec.yaml
4.0.7 was just published, but a dependency conflict around macros causes the published code to cause failures during static analysis.
This PR downgrades the version of the analyzer in order to avoid the conflict. See https://github.com/dart-lang/pub-dev/issues/7855 for details. Note that no failures are seen locally.
Hello @sigurdm, I'll land this now because of the failing static analysis on pub.dev!
=> Update dependencies again

reflectable/CHANGELOG.md, reflectable/analysis_options.yaml, reflectable/doc/TheDesignOfReflectableCapabilities.md, reflectable/example/example.dart, reflectable/lib/capability.dart, reflectable/lib/mirrors.dart, reflectable/lib/reflectable.dart, reflectable/lib/reflectable_builder.dart, reflectable/lib/src/builder_implementation.dart, reflectable/lib/src/fixed_point.dart, reflectable/lib/src/reflectable_builder_based.dart, reflectable/lib/src/reflectable_errors.dart, reflectable/pubspec.yaml
This PR updates reflectable to use analyzer 6.11.0 and lints 5.1.0. It fixes issue #291 (such that metadata of an enum value can be obtained). It also changes the implementation of reflectable to follow the style defined by the lints `omit_obvious_local_variable_types` and `specify_nonobvious_local_variable_types`. Finally, it prepares reflectable for release as version 4.0.11.
=> Update dependencies, fix 291, use 'obvious' style for local variable types

reflectable/CHANGELOG.md, reflectable/analysis_options.yaml, reflectable/lib/src/builder_implementation.dart, reflectable/pubspec.yaml
The dependency upgrades in 4.0.11 caused no issues locally, but on github they cause failures of basically all the score related checks (pub version resolution fails with respect to some macro packages). This PR changes the dependency on the analyzer to 6.8.0 and lints to 5.0.0, and reverts some changes that were required with analyzer 6.11.0 but which cause errors with analyzer 6.8.0.
=> Revert deps to analyzer 6.8.0

reflectable/CHANGELOG.md, reflectable/lib/capability.dart, reflectable/lib/mirrors.dart, reflectable/lib/reflectable.dart, reflectable/lib/reflectable_builder.dart, reflectable/lib/src/builder_implementation.dart, reflectable/lib/src/element_capability.dart, reflectable/lib/src/incompleteness.dart, reflectable/lib/src/reflectable_base.dart, reflectable/lib/src/reflectable_builder_based.dart, reflectable/pubspec.yaml, test_reflectable/build.yaml
This PR changes the version of the analyzer to ^7.0.0, such that there is no dependency on `_macros` (which doesn't exist with Flutter 3.35, so we really need this step).
It makes minimal changes with respect to the new element model (`Element2`), just enough to make the code generator and generated code work in this new context. This implies that there will be another update where reflectable switches to the new element model (which will allow reflectable to use yet newer versions of the analyser).
This PR also prepares reflectable for being published as version 4.0.14.
=> Update reflectable to work with Flutter 3.35
